# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseMessenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseMessenger

#Firebase
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'

#Snapkit
pod 'SnapKit', '~> 5.6.0'

#Rx
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'

end
